# Data Cleaning and Preprocessing

## Introduction

This project focuses on cleaning and preprocessing a retail sales dataset to make it suitable for further analysis.

The dataset is examined for missing values, duplicate records, inconsistent formatting, outliers, and incorrect data types.

Each data cleaning decision is documented and justified to produce a clean and analysis-ready dataset.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("retail_sales.csv")

df.head()

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0

## Before Cleaning

Before making any changes, the dataset is examined to establish its original quality.

The following information is recorded:
- Number of rows and columns
- Missing values
- Duplicate rows
- Data types
- Potential value range anomalies

In [3]:
print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Dataset shape: (2000, 11)

Missing values:
transactions_id     0
sale_date           0
sale_time           0
customer_id         0
gender              0
age                10
category            0
quantiy             3
price_per_unit      3
cogs                3
total_sale          3
dtype: int64

Duplicate rows:
0

Data types:
transactions_id      int64
sale_date              str
sale_time              str
customer_id          int64
gender                 str
age                float64
category               str
quantiy            float64
price_per_unit     float64
cogs               float64
total_sale         float64
dtype: object

In [4]:
print("Dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:")
print(df.duplicated().sum())
print("\nData types:")
print(df.dtypes)

Dataset shape: (2000, 11)

Missing values:
transactions_id     0
sale_date           0
sale_time           0
customer_id         0
gender              0
age                10
category            0
quantiy             3
price_per_unit      3
cogs                3
total_sale          3
dtype: int64

Duplicate rows:
0

Data types:
transactions_id      int64
sale_date              str
sale_time              str
customer_id          int64
gender                 str
age                float64
category               str
quantiy            float64
price_per_unit     float64
cogs               float64
total_sale         float64
dtype: object

## Data Quality Report

The initial inspection identified several data quality issues in the dataset.

### Identified Issues

1. Missing values are present in the `age`, `quantiy`, `price_per_unit`, `cogs`, and `total_sale` columns.
2. No duplicate records were found.
3. `sale_date` and `sale_time` are stored as string values and require appropriate date/time data types.
4. Numerical columns should be checked for unusual or invalid values.
5. Categorical columns such as `gender` and `category` should be checked for inconsistent formatting.

In [5]:
print("Gender values:")
print(df["gender"].value_counts())

print("\nCategory values:")
print(df["category"].value_counts())

Gender values:
gender
Female    1020
Male       980
Name: count, dtype: int64

Category values:
category
Clothing       702
Electronics    684
Beauty         614
Name: count, dtype: int64

In [6]:
df[[
    "age",
    "quantiy",
    "price_per_unit",
    "cogs",
    "total_sale"
]].describe()

               age      quantiy  price_per_unit         cogs   total_sale
count  1990.000000  1997.000000     1997.000000  1997.000000  1997.000000
mean     41.343216     2.512769      180.117677    95.023886   456.544817
std      13.668167     1.132708      189.685225   121.898695   560.101381
min      18.000000     1.000000       25.000000     6.250000    25.000000
25%      29.000000     1.000000       30.000000    13.000000    60.000000
50%      42.000000     3.000000       50.000000    27.500000   150.000000
75%      53.000000     4.000000      300.000000   147.000000   900.000000
max      64.000000     4.000000      500.000000   620.000000  2000.000000

In [7]:
print("Sample sale dates:")
print(df["sale_date"].head())

print("\nSample sale times:")
print(df["sale_time"].head())

Sample sale dates:
0    2022-11-05
1    2022-07-09
2    2022-12-12
3    2022-01-06
4    2022-11-14
Name: sale_date, dtype: str

Sample sale times:
0    10:47:00
1    11:00:00
2    10:48:00
3    08:53:00
4    08:35:00
Name: sale_time, dtype: str

In [8]:
print("Gender values:")
print(df["gender"].value_counts())

print("\nCategory values:")
print(df["category"].value_counts())

Gender values:
gender
Female    1020
Male       980
Name: count, dtype: int64

Category values:
category
Clothing       702
Electronics    684
Beauty         614
Name: count, dtype: int64

In [9]:
df[[
    "age",
    "quantiy",
    "price_per_unit",
    "cogs",
    "total_sale"
]].describe()

               age      quantiy  price_per_unit         cogs   total_sale
count  1990.000000  1997.000000     1997.000000  1997.000000  1997.000000
mean     41.343216     2.512769      180.117677    95.023886   456.544817
std      13.668167     1.132708      189.685225   121.898695   560.101381
min      18.000000     1.000000       25.000000     6.250000    25.000000
25%      29.000000     1.000000       30.000000    13.000000    60.000000
50%      42.000000     3.000000       50.000000    27.500000   150.000000
75%      53.000000     4.000000      300.000000   147.000000   900.000000
max      64.000000     4.000000      500.000000   620.000000  2000.000000

In [10]:
print("Sample sale dates:")
print(df["sale_date"].head())

print("\nSample sale times:")
print(df["sale_time"].head())

Sample sale dates:
0    2022-11-05
1    2022-07-09
2    2022-12-12
3    2022-01-06
4    2022-11-14
Name: sale_date, dtype: str

Sample sale times:
0    10:47:00
1    11:00:00
2    10:48:00
3    08:53:00
4    08:35:00
Name: sale_time, dtype: str

## Handling Missing Values

The dataset contains missing values in both customer-level and transaction-level fields.

Missing values in the `age` column are replaced using the median age because age is a numerical customer attribute and the median is less sensitive to extreme values.

Rows containing missing values in `quantiy`, `price_per_unit`, `cogs`, or `total_sale` are removed because these transaction-level fields are required for accurate sales and financial analysis. Imputing these values could introduce inaccurate assumptions into the dataset.

In [11]:
# Store the original number of rows
rows_before = len(df)

print("Rows before cleaning:", rows_before)

Rows before cleaning: 2000

In [12]:
# Fill missing age values with the median
df["age"] = df["age"].fillna(df["age"].median())

# Remove rows with missing transaction values
df = df.dropna(
    subset=["quantiy", "price_per_unit", "cogs", "total_sale"]
)

# Check missing values after cleaning
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
transactions_id    0
sale_date          0
sale_time          0
customer_id        0
gender             0
age                0
category           0
quantiy            0
price_per_unit     0
cogs               0
total_sale         0
dtype: int64

In [13]:
print("Rows after missing-value cleaning:", len(df))

print("\nTotal missing values:",
      df.isnull().sum().sum())

Rows after missing-value cleaning: 1997

Total missing values: 0

## Handling Duplicate Records

Duplicate records were checked to ensure that the same transaction was not recorded more than once.

The dataset contained no duplicate rows. Therefore, no records were removed during duplicate handling.

In [14]:
# Check duplicate records before removal
duplicate_count_before = df.duplicated().sum()

print("Duplicate rows before removal:", duplicate_count_before)

# Remove duplicate rows
df = df.drop_duplicates().copy()

# Check duplicate records after removal
duplicate_count_after = df.duplicated().sum()

print("Duplicate rows after removal:", duplicate_count_after)

Duplicate rows before removal: 0
Duplicate rows after removal: 0

## Standardizing Inconsistent Formatting

Categorical columns were checked for inconsistent formatting such as extra spaces and inconsistent capitalization.

The `gender` and `category` columns are standardized by removing unnecessary spaces and applying consistent capitalization.

The `sale_date` column is converted from string format to a proper datetime format for accurate date-based analysis.

In [15]:
# Standardize categorical columns
df["gender"] = df["gender"].str.strip().str.title()
df["category"] = df["category"].str.strip().str.title()

# Convert sale_date to datetime
df["sale_date"] = pd.to_datetime(df["sale_date"], errors="coerce")

# Display the results
print("Gender values:")
print(df["gender"].unique())

print("\nCategory values:")
print(df["category"].unique())

print("\nSale date data type:")
print(df["sale_date"].dtype)

Gender values:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Category values:
<StringArray>
['Clothing', 'Beauty', 'Electronics']
Length: 3, dtype: str

Sale date data type:
datetime64[us]

## Outlier Detection Using IQR

Outliers are detected using the Interquartile Range (IQR) method.

For each numerical column, the first quartile (Q1) and third quartile (Q3) are calculated.

The IQR is calculated as:

IQR = Q3 - Q1

The lower and upper boundaries are:

Lower Bound = Q1 - 1.5 × IQR
Upper Bound = Q3 + 1.5 × IQR

Values outside these boundaries are identified as potential outliers.

In [16]:
# Numerical columns for outlier detection
numeric_cols = [
    "age",
    "quantiy",
    "price_per_unit",
    "cogs",
    "total_sale"
]

outlier_summary = []

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()
    
    outlier_summary.append({
        "Column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": outliers
    })

outlier_df = pd.DataFrame(outlier_summary)

outlier_df

           Column    Q1     Q3    IQR  Lower Bound  Upper Bound  Outlier Count
0             age  29.0   53.0   24.0         -7.0         89.0              0
1         quantiy   1.0    4.0    3.0         -3.5          8.5              0
2  price_per_unit  30.0  300.0  270.0       -375.0        705.0              0
3            cogs  13.0  147.0  134.0       -188.0        348.0             87
4      total_sale  60.0  900.0  840.0      -1200.0       2160.0              0

In [17]:
# Calculate IQR boundaries for cogs
Q1 = df["cogs"].quantile(0.25)
Q3 = df["cogs"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Get potential cogs outliers
cogs_outliers = df[
    (df["cogs"] < lower_bound) |
    (df["cogs"] > upper_bound)
]

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("Number of potential outliers:", len(cogs_outliers))

print("\nPotential cogs outliers:")
print(cogs_outliers[["cogs", "quantiy", "price_per_unit", "total_sale"]].head(20))

Lower Bound: -188.0
Upper Bound: 348.0
Number of potential outliers: 87

Potential cogs outliers:
       cogs  quantiy  price_per_unit  total_sale
1302  363.0      3.0           300.0       900.0
1304  372.0      1.0           300.0       300.0
1318  570.0      4.0           500.0      2000.0
1321  480.0      1.0           500.0       500.0
1322  555.0      4.0           500.0      2000.0
1325  530.0      1.0           500.0       500.0
1327  525.0      4.0           500.0      2000.0
1332  605.0      4.0           500.0      2000.0
1345  354.0      4.0           300.0      1200.0
1351  366.0      1.0           300.0       300.0
1352  595.0      2.0           500.0      1000.0
1353  535.0      2.0           500.0      1000.0
1354  540.0      1.0           500.0       500.0
1356  620.0      1.0           500.0       500.0
1360  369.0      4.0           300.0      1200.0
1374  375.0      3.0           300.0       900.0
1391  600.0      4.0           500.0      2000.0
1393  480.0      4.0           500.0      2000.0
1401  570.0      4.0           500.0      2000.0
1404  615.0      4.0           500.0      2000.0

## Outlier Treatment Decision

The IQR method identified 87 potential outliers in the `cogs` column.

These values were inspected along with the corresponding `quantiy`, `price_per_unit`, and `total_sale` values.

The potential outliers represent higher-cost transactions and fall within the observed business ranges of the dataset. They do not appear to be invalid or data-entry errors.

Therefore, the identified `cogs` outliers are retained rather than removed or capped.

No outliers were removed from the dataset.

## Data Type Correction

The data types of the columns are corrected to ensure that each variable is stored in an appropriate format.

- Transaction and customer IDs are treated as identifiers.
- `age` and `quantiy` are converted to integer values.
- `price_per_unit`, `cogs`, and `total_sale` remain numerical values.
- `sale_date` is stored as a datetime value.
- `gender` and `category` are stored as string values.

In [18]:
# Correct data types

df["transactions_id"] = df["transactions_id"].astype("string")
df["customer_id"] = df["customer_id"].astype("string")

df["age"] = df["age"].astype("int64")
df["quantiy"] = df["quantiy"].astype("int64")

df["gender"] = df["gender"].astype("string")
df["category"] = df["category"].astype("string")

df["price_per_unit"] = df["price_per_unit"].astype("float64")
df["cogs"] = df["cogs"].astype("float64")
df["total_sale"] = df["total_sale"].astype("float64")

In [19]:
print("Data types after correction:")
print(df.dtypes)

Data types after correction:
transactions_id            string
sale_date          datetime64[us]
sale_time                     str
customer_id                string
gender                     string
age                         int64
category                   string
quantiy                     int64
price_per_unit            float64
cogs                      float64
total_sale                float64
dtype: object

## Before vs After Cleaning Summary

The dataset quality is compared before and after the cleaning process.

The comparison includes the total number of missing values, duplicate records, number of rows, and data type accuracy.

The final dataset should contain no missing values or duplicate records, while the important columns should have appropriate data types.

In [20]:
# Load the original dataset for comparison
df_original = pd.read_csv("retail_sales.csv")

# Before-cleaning statistics
rows_before = len(df_original)
missing_before = df_original.isnull().sum().sum()
duplicates_before = df_original.duplicated().sum()

# After-cleaning statistics
rows_after = len(df)
missing_after = df.isnull().sum().sum()
duplicates_after = df.duplicated().sum()

print("BEFORE CLEANING")
print("Rows:", rows_before)
print("Total missing values:", missing_before)
print("Duplicate rows:", duplicates_before)

print("\nAFTER CLEANING")
print("Rows:", rows_after)
print("Total missing values:", missing_after)
print("Duplicate rows:", duplicates_after)

BEFORE CLEANING
Rows: 2000
Total missing values: 22
Duplicate rows: 0

AFTER CLEANING
Rows: 1997
Total missing values: 0
Duplicate rows: 0

In [21]:
# Create before vs after summary table

summary = pd.DataFrame({
    "Metric": [
        "Number of rows",
        "Total missing values",
        "Duplicate rows"
    ],
    "Before Cleaning": [
        rows_before,
        missing_before,
        duplicates_before
    ],
    "After Cleaning": [
        rows_after,
        missing_after,
        duplicates_after
    ]
})

summary

                 Metric  Before Cleaning  After Cleaning
0        Number of rows             2000            1997
1  Total missing values               22               0
2        Duplicate rows                0               0

In [22]:
print("Final data types:")
print(df.dtypes)

Final data types:
transactions_id            string
sale_date          datetime64[us]
sale_time                     str
customer_id                string
gender                     string
age                         int64
category                   string
quantiy                     int64
price_per_unit            float64
cogs                      float64
total_sale                float64
dtype: object

## Saving the Cleaned Dataset

After completing the data cleaning and preprocessing steps, the cleaned dataset is saved as a new CSV file.

The original dataset is preserved, and the cleaned dataset is saved separately for future analysis.

In [23]:
# Save the cleaned dataset as a new CSV file

output_file = "retail_sales_cleaned.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully as:", output_file)

Cleaned dataset saved successfully as: retail_sales_cleaned.csv

In [24]:
# Verify the cleaned dataset

cleaned_df = pd.read_csv(output_file)

print("Cleaned dataset shape:", cleaned_df.shape)

print("\nTotal missing values:")
print(cleaned_df.isnull().sum().sum())

print("\nDuplicate rows:")
print(cleaned_df.duplicated().sum())

Cleaned dataset shape: (1997, 11)

Total missing values:
0

Duplicate rows:
0

# Final Data Cleaning Summary

The retail sales dataset was successfully cleaned and preprocessed.

### Cleaning activities performed

1. **Missing values**
   - Missing `age` values were replaced with the median age.
   - Rows with missing transaction-related values (`quantiy`, `price_per_unit`, `cogs`, and `total_sale`) were removed.
   - Total missing values after cleaning: **0**.

2. **Duplicate records**
   - Duplicate rows were checked.
   - No duplicate records were found.
   - Therefore, no duplicate rows were removed.

3. **Formatting standardization**
   - `gender` and `category` were standardized by removing unnecessary spaces and applying consistent capitalization.
   - `sale_date` was converted to a datetime format.

4. **Outlier detection**
   - The IQR method was used to detect potential outliers.
   - 87 potential outliers were identified in the `cogs` column.
   - These values were inspected and retained because they appeared to represent legitimate high-cost transactions.

5. **Data type correction**
   - Identifier columns were converted to string.
   - `age` and `quantiy` were converted to integer values.
   - Numerical financial columns were maintained as numerical data types.
   - `sale_date` was converted to datetime.
   - Categorical columns were converted to string.

6. **Final dataset**
   - Original number of rows: **2000**
   - Final number of rows: **1997**
   - Total missing values: **0**
   - Duplicate rows: **0**

The cleaned dataset has been saved as `retail_sales_cleaned.csv

## Conclusion

The retail sales dataset was successfully cleaned and prepared for further analysis.

Missing values, duplicate records, inconsistent formatting, potential outliers, and inappropriate data types were systematically examined and addressed.

The final dataset contains 1,997 records with no missing values or duplicate rows. Potential outliers in the `cogs` column were retained after inspection because they were considered valid business observations.

The cleaned dataset was saved separately as `retail_sales_cleaned.csv`, preserving the original dataset and providing an analysis-ready version for future use.